site_name: AppSeed
site_description: Official Documentation - App Generator | AppSeed
site_url: https://docs.appseed.us/
repo_url: https://github.com/app-generator/docs/
google_analytics: ['UA-104843706-2', 'docs.appseed.us']

markdown_extensions:
  - meta

nav:
- About:  
  - 'App Generator'   : 'app-generator/index.md'   
  - 'Geek Glossary'   : 'what-is/index.md'   

- Backends:  
  - 'Backends'        : 'backends/index.md'   
  - 'Starter Express' : 'backends/express-starter.md'   
  - 'Starter Flask'   : 'backends/flask-starter.md'   
  - 'Starter Laravel' : 'backends/laravel-starter.md'   

- Apps:  
  - 'Full-Stack Apps' : 'apps/index.md'   
  - 'React Apps'      : 'apps/react/index.md'   
  - 'Vue.js Apps'     : 'apps/vuejs/index.md'   
  - 'Flask Apps'      : 'apps/flask-apps/index.md'   
  - 'GatsbyJS Apps'   : 'apps/gatsbyjs/index.md'   

- Made with:  
  - 'Argon Design'    : 'apps/argon-design-system/index.md'   
  - 'Bulma CSS'       : 'apps/bulma-css/index.md'   
  - 'HTML5 Up Design' : 'apps/html5up/index.md'   
