site_name: AppSeed
site_description: Official Documentation | AppSeed
site_url: https://docs.appseed.us/
repo_url: https://github.com/app-generator/docs/
google_analytics: ['UA-104843706-2', 'docs.appseed.us']

markdown_extensions:
  - meta

nav:
- Generator:  
  - 'App Generator'     : 'app-generator/index.md'   

- Web Apps:  
  - 'Admin Dashboards'  : 'admin-dashboards/index.md'   
  - 'Static Sites'      : 'apps/static-site/index.md'   
  - 'JAMstack'          : 'apps/jamstack/index.md'   
  - 'Flask Apps'        : 'apps/flask-apps/index.md'   

- Boilerplate Code:  
  - 'Boilerplate Code'    : 'boilerplate-code/index.md'   
  - 'Nodejs Starter'      : 'boilerplate-code/nodejs-starter'   
  - 'Laravel Boilerplate' : 'boilerplate-code/laravel-boilerplate'   
  - 'Flask Boilerplate'   : 'boilerplate-code/flask-boilerplate'   

